### PR TITLE
Replace Pack200 with newer patching method.

### PR DESCRIPTION
**Pull request by KorewaLidesu**
Need test before merge

Pack200 deprecated since Java 11 and removed since Java 14. This will allow the mod to run on newer Java above 14
Mainly fix for https://github.com/Su5eD/IC2-Patcher/issues/14

### CODE REVIEW

**Comment by Kanzaji** [comment]
I will test this out in a free time, but the final opinion on this I will left to original author @Su5eD

**Review by Kanzaji — CHANGES_REQUESTED** [review]
After compilling the mod and launching my test instance and E2E modpack, none of the current patches were applied, and additionally because of that the game crashed on exit from the world.

Here is the log if that will help you resolve the issues 😄
[latest.log](https://github.com/Su5eD/IC2-Patcher/files/13633885/latest.log)

**Comment by KorewaLidesu** [comment]
Can ya upload the build up here?

**Comment by Kanzaji** [comment]
> Can ya upload the build up here?

Unfortunately I will be able to do so in few hours, had only a bit of time last hour to test this out, and im currently without access to pc 😅

I've got an idea however, and you might try regenerating binary patches, as it's possible old ones aren't compatible? If that works just add them to the PR.

**Comment by KorewaLidesu** [comment]
> After compilling the mod and launching my test instance and E2E modpack, none of the current patches were applied, and additionally because of that the game crashed on exit from the world.
> 
> Here is the log if that will help you resolve the issues 😄 [latest.log](https://github.com/Su5eD/IC2-Patcher/files/13633885/latest.log)

Oh yes I just realize that the version you use is different from gradle script one, that why it won't apply the patch. I will commit both patchh just in case

**Comment by KorewaLidesu** [comment]
> Back home and uploading the testing build I've tried 😄 [ic2patcher-2.0.8.zip](https://github.com/Su5eD/IC2-Patcher/files/13637458/ic2patcher-2.0.8.zip)

Yep, seem like both patches aren't correct version from what I build. I will build the patches and manual upload it instead 🙆‍♂️

**Comment by Kanzaji** [comment]
> P/s: seem like making patch for 164 will be abit difficult
What do mean by that 👀?

**Comment by Kanzaji** [comment]
From what I can tell from the quick testing on my testing instance, 164 and 221 IC2 work just fine 😄
I will leave a review after I test out Enigmatica 2 Expert, but I don't see a reason it won't work in there.

**Comment by KorewaLidesu** [comment]
> From what I can tell from the quick testing on my testing instance, 164 and 221 IC2 work just fine 😄 I will leave a review after I test out Enigmatica 2 Expert, but I don't see a reason it won't work in there.

I checked the one you upload and seem like the patches is the one that get compressed by Pack200 so they can't be read unless you unpack them first. The way I check is simple use 7zip which using LZMA compression method.

This is patch packed by Pack200.
image
This is patch not packed by Pack200
image

**Review by Kanzaji — APPROVED** [review]
After update of the binary Patches, I was able to successfully launch both my test instance and E2E modpack (on the end-game save) so from my testing it appears to work as expected😄

**Review by Su5eD — APPROVED** [review]

**Comment by Kanzaji** [comment]
I should go ahead and merge this as I have a bit of free time 😅 Thanks for the contribution!

**Pull request merged**
